name: Daily Commit Workflow

on:
  schedule:
    - cron: "0 3 * * *"  # This will run the workflow once per day at 3 AM UTC
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: harshavardhan.karimikonda@gramener.com
        run: |
          # Create or modify a file in the repository
          echo "This file was updated by the GitHub Actions workflow at $(date)" >> update.txt
          
          # Configure git with user details
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Add, commit, and push the changes using the GITHUB_TOKEN for authentication
          git add update.txt
          git commit -m "Daily update commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

      - name: "Debugging Step - Email: harshavardhan.karimikonda@gramener.com"
        run: |
          echo "Current branch: $(git branch --show-current)"
          echo "Repository URL: $(git remote get-url origin)"
          git status
